/************************************************************************
 *  File: nevispcie_diag.c
 *
 *  Sample user-mode diagnostics application for accessing NEVISPCI
 *  devices using WinDriver's API.
 *  Code was generated by DriverWizard v11.00.
 *  Code was edited by jcrespo to remove unused functions which conflict with v12.60.
 *
 *  Jungo Confidential. Copyright (c) 2012 Jungo Ltd.  http://www.jungo.com
 *************************************************************************/
#ifndef LINUX
#define LINUX
#endif

#include "wdc_defs.h"
#include "status_strings.h"
#include "nevispci_lib.h"


extern "C" {
    //Import wizard generated functions from windriver library
    WDC_DEVICE_HANDLE deviceFindAndOpen(DWORD dwVendorId, DWORD dwDeviceId, DWORD dwBus);
    BOOL deviceFind(DWORD dwVendorId, DWORD dwDeviceId, DWORD dwBus, WD_PCI_SLOT *pSlot);
    WDC_DEVICE_HANDLE deviceOpen(const WD_PCI_SLOT *pSlot);
    void deviceClose(WDC_DEVICE_HANDLE hDev);
}
