#!/bin/sh


export A3818_PID=`/usr/sbin/lsof /dev |& grep a3818 | grep -oP '^[^0-9]*\K[0-9]+' | uniq`

set ctr=0
echo " "
if [ -n "$A3818_PID" ]; then 
  echo "Users of /dev/a3818:"
  for USER_PID in $A3818_PID
  do 
    ps --no-headers -wwwf $USER_PID
    set ctr=$ctr+1
  done
else
  echo "No /dev/a3818 owner found"
fi

echo " "

exit $ctr
